import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Noto_Sans_JP, Roboto } from 'next/font/google';

const notoSansJP = Noto_Sans_JP({
  weight: ['400', '700'], // 必要な重さだけにすると軽量化
  subsets: ['latin'],     // 日本語も対応している（latin でOK）
  display: 'swap',        // FOUT対策
});

export const roboto = Roboto({
  weight: ['700'],
  subsets: ['latin'],
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          `${geistSans.variable} 
          ${geistMono.variable} antialiased
          ${notoSansJP.className} `}
      >
        {children}
      </body>
    </html>
  );
}
